apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-test
  namespace: rhel-lightspeed-ai
spec:
  destination:
    name: in-cluster
    namespace: rhel-lightspeed-ai
  project: default
  source:
    path: "kustomize-guestbook"
    repoURL: 'https://github.com/argoproj/argocd-example-apps'
    targetRevision: master
    kustomize:
      namespace: rhel-lightspeed-ai
  syncPolicy:
    automated:
      selfHeal: true
      allowEmpty: false
    prune: true
