apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rhelaiis-cache
  namespace: rhel-lightspeed-ai
  labels:
    app: rhelaiis
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi