apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rhel-lightspeed-ai

resources:
  - deployment.yaml
  - service.yaml
  - route.yaml

commonLabels:
  app: librespeed
  managed-by: argocd
