apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: openspeedtest
  namespace: rhel-lightspeed-ai
  labels:
    app: openspeedtest
spec:
  to:
    kind: Service
    name: openspeedtest
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect