apiVersion: v1
kind: Service
metadata:
  name: openspeedtest
  namespace: rhel-lightspeed-ai
  labels:
    app: openspeedtest
spec:
  type: ClusterIP
  selector:
    app: openspeedtest
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
  - name: https
    port: 443
    targetPort: 3001
    protocol: TCP