apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: label-studio
  namespace: rhel-lightspeed-ai
  labels:
    app: label-studio
spec:
  to:
    kind: Service
    name: label-studio-ls-app
  port:
    targetPort: service
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
